Repository Adrian-Hawkins/BeanHub, pull requests merged in 2024-03, with the labels that each got.

#4 Added oauth for github
  BeanHub.Client/app/build.gradle.kts
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/Auth.java
Labels: enhancement

#7 Feature/kan 24 jpa
  .github/workflows/API.yml
  .github/workflows/Deploy.yml
  .gitignore
  BeanHub.API/build.gradle.kts
  BeanHub.API/src/main/java/com/bean/api/classes/Person.java
  BeanHub.API/src/main/java/com/bean/api/controllers/AuthController.java
  BeanHub.API/src/main/java/com/bean/api/controllers/HelloController.java
  BeanHub.API/src/main/java/com/bean/api/entities/Ingredient.java
  BeanHub.API/src/main/java/com/bean/api/entities/Rating.java
  BeanHub.API/src/main/java/com/bean/api/entities/Recipe.java
  BeanHub.API/src/main/java/com/bean/api/entities/RecipeIngredients.java
  BeanHub.API/src/main/java/com/bean/api/entities/Unit.java
  BeanHub.API/src/main/java/com/bean/api/entities/User.java
  BeanHub.API/src/main/java/com/bean/api/services/IngredientService.java
  BeanHub.API/src/main/java/com/bean/api/services/RatingService.java
  BeanHub.API/src/main/java/com/bean/api/services/RecipeIngredientsService.java
  BeanHub.API/src/main/java/com/bean/api/services/RecipeService.java
  BeanHub.API/src/main/java/com/bean/api/services/UnitService.java
  BeanHub.API/src/main/java/com/bean/api/services/UserService.java
  BeanHub.API/src/main/resources/application.yml
Labels: enhancement

#9 Bugfix/kan 26 auth fix
  .github/workflows/API.yml
  .github/workflows/Deploy.yml
  BeanHub.API/src/main/java/com/bean/api/controllers/AuthController.java
  BeanHub.API/src/test/java/com/bean/api/entities/IngredientTest.java
  BeanHub.API/src/test/java/com/bean/api/entities/RatingTest.java
  BeanHub.API/src/test/java/com/bean/api/entities/RecipeIngredientsTest.java
  BeanHub.API/src/test/java/com/bean/api/entities/RecipeTest.java
  BeanHub.API/src/test/java/com/bean/api/entities/UnitTest.java
  BeanHub.API/src/test/java/com/bean/api/entities/UserTest.java
  BeanHub.API/src/test/java/com/bean/api/services/IngredientServiceTest.java
  BeanHub.API/src/test/java/com/bean/api/services/RatingServiceTest.java
  BeanHub.API/src/test/java/com/bean/api/services/RecipeIngredientsServiceTest.java
  BeanHub.API/src/test/java/com/bean/api/services/RecipeServiceTest.java
  BeanHub.API/src/test/java/com/bean/api/services/UnitServiceTest.java
  BeanHub.API/src/test/java/com/bean/api/services/UserServiceTest.java
  BeanHub.Client/app/src/main/java/client/util/Auth.java
  BeanHub.Client/app/src/test/java/client/AppTest.java
Labels: bug

#13 Client input fix
  BeanHub.API/src/main/java/com/bean/api/controllers/RecipePostController.java
  BeanHub.API/src/main/java/com/bean/api/entities/RecipeIngredients.java
  BeanHub.API/src/main/java/com/bean/api/requests/postRecipeRequest.java
  BeanHub.API/src/main/java/com/bean/api/services/IngredientService.java
  BeanHub.API/src/main/java/com/bean/api/services/UnitService.java
  BeanHub.Client/app/build.gradle.kts
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/PostRecipe.java
  BeanHub.Client/gradle/wrapper/gradle-wrapper.jar
  BeanHub.Client/gradle/wrapper/gradle-wrapper.properties
  BeanHub.Client/gradlew
  README.md
  SQL/V202403091814__ChangeRecipeIngredientTable.sql
Labels: bug, enhancement

#19 Kan 31 implement view past recipes
  BeanHub.API/src/main/java/com/bean/api/controllers/ViewPastRecipesController.java
  BeanHub.API/src/main/java/com/bean/api/services/ViewPastRecipesService.java
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/Auth.java
  BeanHub.Client/app/src/main/java/client/util/Recipe.java
  BeanHub.Client/app/src/main/java/client/util/ViewPastRecipes.java
  SQL/V202403101100__DeleteUnNeededTables.sql
Labels: bug, enhancement

#20 Feature/kan 11 recipe post
  BeanHub.API/src/main/java/com/bean/api/entities/Ingredient.java
  BeanHub.API/src/test/java/com/bean/api/entities/IngredientTest.java
  BeanHub.API/src/test/java/com/bean/api/services/IngredientServiceTest.java
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/helpers/JSONParser.java
  BeanHub.Client/app/src/main/java/client/util/Auth.java
  BeanHub.Client/app/src/main/java/client/util/PostRecipe.java
Labels: bug

#28 Feature/basic feed
  BeanHub.API/src/main/java/com/bean/api/controllers/FeedController.java
  BeanHub.API/src/main/java/com/bean/api/entities/Recipe.java
  BeanHub.API/src/main/java/com/bean/api/services/RatingService.java
Labels: enhancement

#29 Feature/explore
  BeanHub.API/src/main/java/com/bean/api/controllers/ExploreController.java
  BeanHub.API/src/main/java/com/bean/api/services/RecipeService.java
Labels: enhancement

#30 feat: edit recipe
  BeanHub.API/src/main/java/com/bean/api/controllers/RecipeController.java
  BeanHub.API/src/main/java/com/bean/api/entities/Recipe.java
  BeanHub.API/src/main/java/com/bean/api/services/RatingService.java
  BeanHub.API/src/main/java/com/bean/api/services/RecipeService.java
  BeanHub.API/src/test/java/com/bean/api/entities/RecipeTest.java
  BeanHub.API/src/test/java/com/bean/api/services/RatingServiceTest.java
  BeanHub.API/src/test/java/com/bean/api/services/RecipeServiceTest.java
  BeanHub.Client/app/src/main/java/client/util/EditRecipe.java
Labels: enhancement

#27 Kan 12 implement delete recipe
  .gitignore
  BeanHub.API/src/main/java/com/bean/api/controllers/ViewPastRecipesController.java
  BeanHub.API/src/main/java/com/bean/api/services/ViewPastRecipesService.java
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/Recipe.java
  BeanHub.Client/app/src/main/java/client/util/ViewPastRecipes.java
  README.md
Labels: enhancement

#31 Feature/kan 37 jwt
  BeanHub.API/build.gradle.kts
  BeanHub.API/src/main/java/com/bean/api/config/InterceptorConfig.java
  BeanHub.API/src/main/java/com/bean/api/interceptors/AuthInterceptor.java
  BeanHub.API/src/main/java/com/bean/api/util/ValidateToken.java
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/Auth.java
  BeanHub.Client/app/src/main/java/client/util/EditRecipe.java
  BeanHub.Client/app/src/main/java/client/util/PostRecipe.java
Labels: enhancement

#36 Feature/kan 35 colors
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/Auth.java
  BeanHub.Client/app/src/main/java/client/util/PostRecipe.java
Labels: enhancement

#51 Kan 13 rate recipe
  .github/workflows/packageRelease.yml
  BeanHub.API/src/main/java/com/bean/api/controllers/RecipeController.java
  BeanHub.API/src/main/java/com/bean/api/services/RecipeService.java
  BeanHub.API/src/main/java/com/bean/api/services/UserService.java
  BeanHub.Client/app/src/main/java/client/util/RateRecipe.java
  BeanHub.Client/app/src/main/java/client/util/ViewPastRecipes.java
Labels: enhancement

#54 Updated readme
  README.md
Labels: documentation

#55 Kan 20 executable client
  .github/workflows/Client.yml
  BeanHub.Client/app/build.gradle.kts
  BeanHub.Client/build.gradle
Labels: enhancement

#63 Post demo kay
  BeanHub.API/src/main/java/com/bean/api/enums/SortOption.java
  BeanHub.API/src/main/java/com/bean/api/requests/RecipeAverageRatingRequest.java
  BeanHub.API/src/main/java/com/bean/api/services/RecipeService.java
  BeanHub.Client/app/src/main/java/client/App.java
  BeanHub.Client/app/src/main/java/client/util/ViewExplore.java
Labels: bug

#64 Post demo moshe
  BeanHub.API/src/main/java/com/bean/api/controllers/FeedController.java
  BeanHub.API/src/main/java/com/bean/api/services/RatingService.java
Labels: bug
